'use client';
import {useState,useEffect,type FormEvent} from 'react';
import {ArrowLeft,Plus,Upload,Trash2,ExternalLink,ArrowUp,ArrowDown,Save,Mail,Check,RefreshCw} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {Profile,Project} from '@/lib/content';
type Message={id:string;name:string;email:string;subject:string;message:string;created_at:number;read:boolean;email_status:string};
const blank=():Project=>({id:crypto.randomUUID(),title:'',category:'Web application',description:'',stack:'',liveUrl:'',repoUrl:'',image:'',imageAlt:'',problem:'',solution:'',role:'',published:false,position:0,cover:'yellow'});
export default function Admin(){const [data,setData]=useState<{profile:Profile;projects:Project[];messages:Message[]}|null>(null),[profile,setProfile]=useState<Profile|null>(null),[edit,setEdit]=useState<Project|null>(null),[preview,setPreview]=useState<Project|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[remove,setRemove]=useState<{action:string;id:string;label:string}|null>(null);
 async function load(){setError('');try{const r=await fetch('/api/admin',{cache:'no-store'}),j=await r.json() as any;if(!r.ok)throw Error(j.error);setData(j);setProfile(j.profile)}catch(e){setError(e instanceof Error?e.message:'Unable to load')}}
 useEffect(()=>{load()},[]);
 async function action(body:unknown){const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json() as any;if(!r.ok)throw Error(j.error||'Could not save');}
 async function mutate(body:unknown,success='Saved.'){setBusy(true);setNotice('');try{await action(body);await load();setNotice(success);return true}catch(e){setNotice(e instanceof Error?e.message:'Could not save');return false}finally{setBusy(false)}}
 async function upload(file:File|undefined,kind:'cv'|'image'){if(!file)return;setBusy(true);setNotice('Uploading…');try{const f=new FormData();f.set('file',file);f.set('kind',kind);const r=await fetch('/api/upload',{method:'POST',body:f}),j=await r.json() as any;if(!r.ok)throw Error(j.error);if(kind==='image')setEdit(p=>p?{...p,image:j.url}:p);setNotice(kind==='cv'?'CV replaced. View and download links now use the new PDF.':'Image uploaded. Add alternative text and save your project.')}catch(e){setNotice(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 async function move(p:Project,d:number){if(!data)return;const i=data.projects.findIndex(x=>x.id===p.id),other=data.projects[i+d];if(!other)return;setBusy(true);try{const list=[...data.projects];[list[i],list[i+d]]=[list[i+d],list[i]];for(let n=0;n<list.length;n++)await action({action:'project',value:{...list[n],position:n}});await load();setNotice('Project order updated.')}catch{setNotice('Could not finish reordering. Reload and try again.')}finally{setBusy(false)}}
 function field(key:keyof Project,label:string,multiline=false){return <div className="field"><label htmlFor={'project-'+key}>{label}</label>{multiline?<textarea id={'project-'+key} value={String(edit?.[key]??'')} onChange={e=>setEdit(p=>p?{...p,[key]:e.target.value}:p)}/>:<input id={'project-'+key} value={String(edit?.[key]??'')} onChange={e=>setEdit(p=>p?{...p,[key]:e.target.value}:p)} required={['title','category','description'].includes(key)}/>}</div>}
 return <main className="admin-wrap"><header className="admin-header"><div><a className="text-button" href="/"><ArrowLeft size={16}/> Portfolio</a><h1>Your workspace<span className="yellow-dot">.</span></h1></div><button className="text-button" onClick={async()=>{const r=await fetch("/api/auth/logout",{method:"POST"});if(r.ok)window.location.assign("/admin/login");else setNotice("Could not sign out. Please retry.")}}>Sign out</button></header><p className="admin-note">Publish your work, update your profile, and keep every conversation in one place.</p><p role="status" aria-live="polite">{notice}</p>{error?<div className="admin-card"><p role="alert">{error}</p><button className="button" onClick={load}>Try again</button></div>:!data?<p className="empty" role="status">Loading your workspace…</p>:<Tabs defaultValue="projects"><TabsList className="admin-tabs"><TabsTrigger value="projects">Projects</TabsTrigger><TabsTrigger value="profile">Profile & links</TabsTrigger><TabsTrigger value="cv">CV</TabsTrigger><TabsTrigger value="inbox">Inbox {data.messages.filter(m=>!m.read).length>0&&<span className="pill">{data.messages.filter(m=>!m.read).length}</span>}</TabsTrigger></TabsList>
 <TabsContent value="projects"><div className="admin-card"><div className="section-heading"><div><h2 style={{fontSize:28}}>Selected work</h2><p>Drafts stay private until you publish them.</p></div><button className="button dark" onClick={()=>setEdit({...blank(),position:data.projects.length})}><Plus size={16}/> Add project</button></div>{data.projects.map((p,i)=><div className="admin-project" key={p.id}><div><h3>{p.title}</h3><small>{p.category} · {p.published?'Published':'Draft'}</small></div><div className="actions" style={{margin:0}}><button className="button small outline" onClick={()=>move(p,-1)} disabled={busy||i===0} aria-label={'Move '+p.title+' up'}><ArrowUp size={14}/></button><button className="button small outline" onClick={()=>move(p,1)} disabled={busy||i===data.projects.length-1} aria-label={'Move '+p.title+' down'}><ArrowDown size={14}/></button><button className="text-button" onClick={()=>setPreview(p)}>Preview</button><button className="button small outline" onClick={()=>setEdit({...p})}>Edit</button><button className="text-button" disabled={busy} onClick={()=>mutate({action:'project',value:{...p,published:!p.published}},p.published?'Project unpublished.':'Project published.')}>{p.published?'Unpublish':'Publish'}</button><button className="text-button" aria-label={'Delete '+p.title} onClick={()=>setRemove({action:'deleteProject',id:p.id,label:p.title})}><Trash2 size={16}/></button></div></div>)}{!data.projects.length&&<p className="empty">Add your first project.</p>}</div></TabsContent>
 <TabsContent value="profile">{profile&&<form className="admin-card" onSubmit={async e=>{e.preventDefault();await mutate({action:'profile',value:profile},'Profile and social links saved.')}}><h2>Profile & contact</h2>{([['name','Full name'],['role','Professional title'],['location','Location'],['email','Contact email'],['phone','Phone (international format, e.g. +923093388296)'],['whatsapp','WhatsApp number (digits only)'],['github','GitHub username']] as const).map(([key,label])=><div className="field" key={key}><label htmlFor={'profile-'+key}>{label}</label><input id={'profile-'+key} required value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></div>)}{(['intro','about'] as const).map(key=><div className="field" key={key}><label htmlFor={'profile-'+key}>{key==='intro'?'Homepage introduction':'About paragraph'}</label><textarea id={'profile-'+key} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})} required/></div>)}<h2 style={{marginTop:40}}>Social link cards</h2><p className="admin-note">Add LinkedIn, Instagram, YouTube, or any HTTPS profile. GitHub data refreshes automatically; other cards use the details you enter. Phone, WhatsApp, and email cards use the contact fields above.</p>{profile.socials.map((s,i)=><div key={s.id} className="admin-card"><div className="field-row"><div className="field"><label htmlFor={'social-name-'+s.id}>Platform</label><input id={'social-name-'+s.id} value={s.name} required onChange={e=>setProfile({...profile,socials:profile.socials.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></div><div className="field"><label htmlFor={'social-label-'+s.id}>Card subtitle</label><input id={'social-label-'+s.id} value={s.label} onChange={e=>setProfile({...profile,socials:profile.socials.map((x,j)=>j===i?{...x,label:e.target.value}:x)})}/></div></div><div className="field"><label htmlFor={'social-url-'+s.id}>Profile URL</label><input id={'social-url-'+s.id} type="url" required value={s.url} onChange={e=>setProfile({...profile,socials:profile.socials.map((x,j)=>j===i?{...x,url:e.target.value}:x)})}/></div><button type="button" className="text-button" onClick={()=>setProfile({...profile,socials:profile.socials.filter((_,j)=>j!==i)})}>Remove card</button></div>)}<button type="button" className="button outline" onClick={()=>setProfile({...profile,socials:[...profile.socials,{id:crypto.randomUUID(),name:'',label:'',url:''}]})}><Plus size={16}/> Add social card</button><div className="actions"><button disabled={busy} className="button dark" type="submit"><Save size={16}/> Save profile</button></div></form>}</TabsContent>
 <TabsContent value="cv"><div className="admin-card"><h2>Your curriculum vitae</h2><p>Upload a PDF to replace the current CV. Both viewing and downloading use the same file.</p><div className="field"><label htmlFor="cv-upload">New CV · PDF · up to 4 MB</label><input id="cv-upload" type="file" accept="application/pdf" disabled={busy} onChange={e=>upload(e.target.files?.[0],'cv')}/></div><div className="actions"><a className="button outline" href="/cv" target="_blank" rel="noopener noreferrer">View current CV <ExternalLink size={16}/></a><a className="button outline" href="/cv?download=1" download="Taimoor_Ali_Waris_CV.pdf">Download current CV</a></div></div></TabsContent>
 <TabsContent value="inbox"><div className="admin-card"><div className="section-heading"><div><h2 style={{fontSize:28}}>Messages</h2><p>Contact form submissions are saved here.</p></div><button className="button small outline" onClick={load}><RefreshCw size={15}/> Refresh</button></div><p className="admin-note">Replies open your email app. Messages are saved before email is attempted. Check each notification status below; failed notifications can be retried.</p>{data.messages.map(m=><article className="admin-card" key={m.id}><span className="kicker">{new Date(m.created_at).toLocaleString()}{!m.read&&' · Unread'}</span><h3 style={{fontSize:22,marginTop:12}}>{m.subject}</h3><p><strong>{m.name}</strong> · {m.email}</p><p className="message-body">{m.message}</p><p className="admin-note">Email notification: {m.email_status||"pending"}</p><div className="actions"><a className="button small dark" href={'mailto:'+m.email+'?subject='+encodeURIComponent('Re: '+m.subject)}><Mail size={14}/> Reply</a>{!m.read&&<button className="button small outline" disabled={busy} onClick={()=>mutate({action:'readMessage',id:m.id},'Marked as read.')}><Check size={14}/> Mark read</button>}{m.email_status!=='sent'&&<button className="button small outline" disabled={busy} onClick={()=>mutate({action:'retryEmail',id:m.id},'Email notification sent.')}>Retry notification</button>}<button className="text-button" onClick={()=>setRemove({action:'deleteMessage',id:m.id,label:'this message'})}><Trash2 size={14}/> Delete</button></div></article>)}{!data.messages.length&&<div className="empty"><Mail style={{margin:'0 auto 15px'}}/><p>No messages yet. New submissions will appear here.</p></div>}</div></TabsContent>
 </Tabs>}
 <Dialog open={!!edit} onOpenChange={open=>{if(!open&&!busy)setEdit(null)}}><DialogContent className="admin-editor"><DialogTitle>Edit project</DialogTitle><DialogDescription>Save as a draft or publish to your portfolio.</DialogDescription>{edit&&<form onSubmit={async(e:FormEvent)=>{e.preventDefault();if(await mutate({action:'project',value:edit},'Project saved.'))setEdit(null)}}>{field('title','Project title')}{field('category','Category')}{field('description','Short description',true)}{field('stack','Technologies (comma-separated)')}{field('liveUrl','Live project URL (HTTPS, optional)')}{field('repoUrl','Source code URL (HTTPS, optional)')}{field('problem','The brief',true)}{field('solution','The approach',true)}{field('role','Your contribution')}<div className="field"><label htmlFor="project-image">Project screenshot · PNG, JPEG, WebP · up to 4 MB</label><input id="project-image" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files?.[0],'image')}/></div>{edit.image&&<><img src={edit.image} alt={edit.imageAlt||'Uploaded screenshot preview'} style={{width:'100%',maxHeight:240,objectFit:'contain'}}/>{field('imageAlt','Screenshot alternative text')}<button type="button" className="text-button" onClick={()=>setEdit({...edit,image:'',imageAlt:''})}>Remove screenshot</button></>}<div className="field"><label htmlFor="cover">Cover color (when no screenshot)</label><Select value={edit.cover||'light'} onValueChange={v=>setEdit({...edit,cover:v==='light'?'':v})}><SelectTrigger id="cover"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="light">Light</SelectItem><SelectItem value="yellow">Yellow</SelectItem><SelectItem value="ink">Charcoal</SelectItem></SelectContent></Select></div><label className="mini-link" style={{margin:'20px 0'}}><Checkbox checked={edit.published} onCheckedChange={v=>setEdit({...edit,published:v===true})}/> Published on portfolio</label><p role="status">{notice}</p><button disabled={busy} className="button dark" type="submit"><Save size={16}/>{busy?'Saving…':'Save project'}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!preview} onOpenChange={o=>!o&&setPreview(null)}><DialogContent className="case-content"><DialogTitle>{preview?.title}</DialogTitle><DialogDescription>{preview?.description}</DialogDescription>{preview&&<><div className="tags">{preview.stack.split(',').map(t=><span key={t}>{t}</span>)}</div><h3>The brief</h3><p>{preview.problem}</p><h3>The approach</h3><p>{preview.solution}</p><h3>My contribution</h3><p>{preview.role}</p>{preview.image&&<img src={preview.image} alt={preview.imageAlt} style={{width:'100%'}}/>}{preview.liveUrl&&<a className="button dark" href={preview.liveUrl} target="_blank" rel="noopener noreferrer">Open live project <ExternalLink size={15}/></a>}</>}</DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={o=>!o&&setRemove(null)}><AlertDialogContent><AlertDialogTitle>Delete {remove?.label}?</AlertDialogTitle><AlertDialogDescription>This removes it from your portfolio workspace. This action cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(remove)await mutate(remove,'Deleted.');setRemove(null)}}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
