export type Project={id:string;title:string;category:string;description:string;stack:string;liveUrl:string;repoUrl:string;image:string;imageAlt:string;problem:string;solution:string;role:string;published:boolean;position:number;cover:string};
export type Social={id:string;name:string;label:string;url:string};
export type Profile={name:string;role:string;intro:string;about:string;email:string;phone:string;whatsapp:string;location:string;github:string;socials:Social[]};
export const initialProfile:Profile={name:'Taimoor Ali Waris',role:'Full Stack Developer',intro:'I turn ideas into useful web applications — from thoughtful React interfaces to the APIs and databases behind them.',about:'I’m a full stack developer based in Lahore and a Computer Science student. I enjoy connecting the details: an intuitive interface, a clear API, and a dependable data model. My experience spans frontend development and MERN applications, with a focus on building practical tools for real workflows.',email:'taimooraliwaris13@gmail.com',phone:'+923093388296',whatsapp:'923093388296',location:'Lahore, Pakistan',github:'taimooraliwaris',socials:[{id:'github',name:'GitHub',label:'@taimooraliwaris',url:'https://github.com/taimooraliwaris'},{id:'linkedin',name:'LinkedIn',label:'Let’s connect professionally',url:'https://www.linkedin.com/in/taimooraliwaris/'}]};
export const initialProjects:Project[]=[
{id:'soomro',title:'Soomro Law Services',category:'Business website',description:'A professional web presence that helps a law services firm explain its expertise and connect with clients.',stack:'HTML, CSS, JavaScript, Bootstrap',liveUrl:'https://www.soomrolawservices.live/',repoUrl:'https://github.com/taimooraliwaris/Soomrolawservices',image:'',imageAlt:'',problem:'Present a law firm’s services clearly and make it easy for prospective clients to take the next step.',solution:'A responsive business website with service information and direct contact paths.',role:'Website development',published:true,position:0,cover:'ink'},
{id:'youtube',title:'YouTube interface',category:'Frontend',description:'An interface recreation exploring responsive video grids, navigation, and familiar browsing patterns.',stack:'HTML, CSS, JavaScript',liveUrl:'',repoUrl:'https://github.com/taimooraliwaris/youtube-clone',image:'',imageAlt:'',problem:'Recreate a familiar browsing experience while practicing responsive frontend development.',solution:'A video-grid interface with structured navigation and reusable layout patterns.',role:'Frontend development · learning project',published:true,position:1,cover:'yellow'},
{id:'chariteams',title:'ChariTeams',category:'Frontend',description:'A charity platform interface with interactive elements for team-based fundraising workflows.',stack:'HTML, CSS, JavaScript',liveUrl:'',repoUrl:'',image:'',imageAlt:'',problem:'Organize charity and fundraising information into an approachable web experience.',solution:'Interactive interface components and a responsive layout for charity coordination.',role:'Frontend development',published:true,position:2,cover:''}
];
